### ISSUE TITLE
XML entities are not encoded correctly

### ISSUE THREAD

**Issue by MattFiler** [x1nixmzeng/AlienBML#1]
Hey!

I know it's been a long time since you released this tool, and I've been meaning to post this here for quite some time... I was wondering if you'd be able to revisit this project to fix a bug with it?

It's really useful and has inspired a lot of good mods for Alien Isolation, but there's one really important BML file that the tool doesn't work with - called "_DIRECTORY_CONTENTS.BML" in the "BINARY_BEHAVIOUR" folder. If we could mod that file it seems that we would be able to change a lot of the AI behaviours and make some really cool mods for the game.

Currently, the tool will extract the file to XML, however when you try to convert it back to BML to use in the game, the tool produces an error.

A fix to this would be absolutely awesome. 

Thanks!

**Comment by MattFiler** [comment]
Ah!

Typical as ever - I post an issue and manage to figure out the issue just two days later when I've been trying to get this to work for months lol.

The issue is that there is a lone ampersand in the _DIRECTORY_CONTENTS.BML file! Replacing it with the HTML character code &amp; allows the converter to export it as an XML/BML file and the game still reads it absolutely fine!

Do you know why the converter didn't like the ampersand? So damn happy its working now though, thanks for making such an awesome tool!

**Comment by x1nixmzeng** [comment]
I'm glad you found a workaround!

This project uses the standard System.XML namespace and I don't think it handles encoding the special XML entities in the text.. If you need support for this, send me this BML file :smile:

**Comment by MattFiler** [comment]
Ah right, it would be awesome if you could figure out a way to fix it. For now I've just uploaded my fixed BML to the mod guide which has the HTML ampersand added, but obviously just being able to use the base game's files would be much easier!

[Here's the file in question.](https://www.mediafire.com/?hrtg0ipohdpr8c9)

Thanks again!

**Comment by x1nixmzeng** [comment]
Thanks - I've fixed the encoding, but this file loses a lot of whitespace when it is repeatedly re-exported. Let me know if this is an issue! I remember the game seemed very picky about retaining BML whitespace when it was released!

**Comment by MattFiler** [comment]
Awesome - much appreciated!
Thanks so much for your help.
